### ISSUE TITLE
Support Knative environment variable for service and version

### ISSUE THREAD

**Issue by steren** [googleapis/cloud-profiler-nodejs#308]
The Knative open source project injects in the user container the variables `K_SERVICE` and `K_REVISION` that contain the equivalent of `GAE_SERVICE` and `GAE_VERSION`.

The profiler should pick them up if they are available and map them to service and version context.

**Comment by steren** [comment]
Ping?

**Comment by nolanmar511** [comment]
This is something we want to do, but probably not something we'll get to until after pre-built binaries for https://github.com/google/pprof-nodejs.

**Comment by aalexand** [comment]
@nolanmar511 This is prioritization, not a dependency, right?

**Comment by nolanmar511** [comment]
Yes -- this is a prioritization.

**Comment by aalexand** [comment]
@steren What do typical values for K_SERVICE and K_REVISION look like? Which regular expression they match, essentially? We'll need to make sure they can be passed as is to the service and version fields. Also, confirm please that these are set before the process start and won't change during the process lifetime.

Other that that, @nolanmar511, the fix is just updating code at https://github.com/googleapis/cloud-profiler-nodejs/blob/84fa342bc5f470ff2ad5961cadea6e69e0875bb0/ts/src/index.ts#L56 from
```
    serviceContext: {
      service: process.env.GAE_SERVICE,
      version: process.env.GAE_VERSION,
    }
```
to
```
    serviceContext: {
      service: process.env.GAE_SERVICE || process.env.K_SERVICE,
      version: process.env.GAE_VERSION || process.env.K_REVISION,
    }
```
which seems like 10 minute fix or am I missing something?

**Comment by nolanmar511** [comment]
It's a quick fix. But a fix that we would probably want to make in all agents -- which makes it a bit bigger of a fix.

**Comment by aalexand** [comment]
Still seems a trivial fix as we read the GAE_* variables in all agents already.

steren@, feel free to also send a PR / CLs for this if you want to get this fixed sooner.

**Comment by steren** [comment]
These env vars are following Kubernetes resource names and follow their requirements.
