### ISSUE TITLE
no line numbers?

### ISSUE THREAD

**Issue by jasonswearingen** [googleapis/cloud-profiler-nodejs#411]
I tried out the profiler and it looks interesting, but I don't see line numbers listed in the output.

Additionally, I don't see any line numbers when looking at the screenshots shown here: https://cloud.google.com/profiler/docs/using-profiler

However, a number of the issues in this repo's tracker mentions improving line numbers...     is there something I'm missing?   I need line numbers because my output has a lot of ```(anonymous)``` stacks so quite hard to track down without an actual line number for the fcn.

**Comment by nolanmar511** [comment]
There is some line number information currently available in the the Node.js profiles. However, the line number information is not currently displayed in the Stackdriver Profiler UI. Also, line numbers in the profile refer to the first line of the function, rather than the line from which the next function in the stack was called or the line number where time was spent or memory was allocated.

It sounds like the existing line numbers should still be helpful for you, though.

To view profile line number information, you can download the profile:
![image](https://user-images.githubusercontent.com/14046562/53025882-ae514f80-3416-11e9-93e1-a44ac385e904.png)

And use the [pprof](https://github.com/google/pprof) command line tool (for example `pprof -http=: -lines /path/to/profile.pb.gz`) to view the profile data. This command line tool is also vendored into golang, and can be called using the command `go tool pprof`.

**Comment by jasonswearingen** [comment]
thank you for the reply.    Yes if possible to show actual line numbers (even just of the function entrypoint) in the UI, it would be a really great improvement.    

I have been trying various NodeJs profilers in the last few days and the Stackdriver Profiler has the most clear and actionable information, which I find surprising as it seems to be sampling based.

FYI I was considering trying pprof but didn't want to go down the rabbit-hole of getting go working.  now that I know this will somewhat solve my issue I'll give it a try if needed (I was able to guess my way to solving my current perf problems without linenumbers)
